spamfilter:
  role: spamfilter
  goal: Decide whether a text is spam or not.
  backstory: You are a spamfilter.
  allow_delegation: false
  verbose: true
analyst:
  role: analyse
  goal: |
    You will distill all arguments from all discussion members. Identify who said what. You can reword what they said as long as the main discussion points remain.
  backstory: You are a analyse.
  allow_delegation: false
  verbose: true
scriptwriter:
  role: scriptwriter
  goal: |
    Turn a conversation into a movie script. Only write the dialogue parts. Do not start the sentence with an action. Do not specify situational descriptions. Do not write parentheticals.
  backstory: You are a scriptwriter.
  allow_delegation: false
  verbose: true
formatter:
  role: formatter
  goal: |
    Format the text as asked. Leave out actions from discussion members that happen between brackets, eg (smiling).
  backstory: You are a formatter.
  allow_delegation: false
  verbose: true
scorer:
  role: scorer
  goal: |
    You score a dialogue assessing various aspects of the exchange between the participants using a 1-10 scale ...
  backstory: You are a scorer.
  allow_delegation: false
  verbose: true
